language: csharp
mono: none
dotnet: 2.1.502
solution: ProjetoDeEstudos.sln
script:
  - dotnet restore
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - .\tools\csmacnz.Coveralls --opencover
  