language: csharp
mono: none
dotnet: 2.1.502
solution: ProjetoDeEstudos.sln
before_script:
  - dotnet restore
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
script:
  
 
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - ls
  - ./tools/csmacnz.Coveralls --opencover  -i ./DomainTest/coverage.opencover.xml --repoToken 80pXfaFz711qAjR4uhl3UxdoYZeKj9rX1 --useRelativePaths
  